pr:
  branches:
    include:
      - develop
  drafts: false

pool:
  vmImage: 'ubuntu-latest'

variables:
  projects: '**/**/*.sln'

stages:
- stage: Build
  displayName: Build & Test

  jobs:
  - job: Build

    steps:
    - task: UseDotNet@2
      displayName: 'Install DotNet'
      inputs:
        packageType: 'sdk'
        version: '3.x'

    - task: DotNetCoreCLI@2
      displayName: 'DotNet Build'
      inputs:
        command: 'build'
        projects: $(projects)
        arguments: '--output $(Build.ArtifactStagingDirectory) $(styleCopEnabled)'

    - task: DotNetCoreCLI@2
      displayName: 'DotNet Tests'
      inputs:
        command: test
        projects:  $(testsProjects)

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      displayName: 'Dotnet Drop Artifacts'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        ArtifactName: 'drop'
        publishLocation: 'Container'
